# Generated by Django 4.0.2 on 2022-02-27 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='location_name',
        ),
    ]
