# Generated by Django 4.0.2 on 2022-02-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_rename_category_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
